version: '3.3'
services:
  api:
    container_name: 'api'
    build: '.'
    ports:
      - '9090:9090'
    depends_on:
      - 'mongo'
  mongo:
    image: 'mongo:latest'
    container_name: 'mongo'
    ports:
      - '27100:27017'